language: node_js

cache:
  yarn: true
  directories:
    - "node_modules"

node_js:
  - node
  - "10"
  - "8"

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn test

before_deploy:
  - git config --local user.name "${GIT_NAME}"
  - git config --local user.email "${GIT_EMAIL}"
  - git remote rm origin
  - git remote add origin https://${GH_TOKEN}@github.com/laurenashpole/postcss-amplify
  - git fetch origin --tags
  - git checkout master
  - git branch --set-upstream-to origin/master master
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null

deploy:
  provider: script
  script: "yarn release"
  skip_cleanup: true
  on:
    node: "10"
